<?php

/**
 * @file
 *   Views sexy exposed module file.
 */

define('SEXY_EXPOSED_PATH', 'sites/all/libraries/ddcl');
define('SEXY_EXPOSED_VERSION', '1.3');

/**
 * Return dropdown-check-list filepath.
 */
function sexy_exposed_get_js() {
  // @TODO: Libraries integration.
  return SEXY_EXPOSED_PATH . '/js/ui.dropdownchecklist-1.3-min.js';
}

/**
 * Return installed version of dropdown-check-list.
 */
function sexy_exposed_get_version() {
  $version = 0;
  $pattern = '#DropDownCheckList v([0-9\.a-z]+)#';

  $ddcl_js = sexy_exposed_get_js();

  // Return the version of ddcl plugin.
  if (file_exists($ddcl_js)) {
    $ddcl_plugin = file_get_contents($ddcl_js, NULL, NULL, 0, 128);
    if (preg_match($pattern, $ddcl_plugin, $matches)) {
      $version = $matches[1];
    }
  }

  return $version;
}

/**
 * Views3 support.
 */

/**
 * Implements hook_views_api().
 */
function sexy_exposed_views_api() {
  return array(
    'api' => 3.0,
  );
}

