<?php

/**
 * @file
 * Taxonomy related stuff
 *
 */

/**
 * Implements hook_menu().
 */
function mez_taxonomy_menu() {
  $items = array();
  $items['admin/config/mez'] = array(
    'title' => 'MEZ',
    'description' => 'Settings for MEZ.',
    'position' => 'left',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/mez/create_instruments_vocabulary'] = array(
    'title' => 'MEZ instruments vocabulary creation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mez_create_instruments_taxonomy_form'),
    'access arguments' => array('administer taxonomy'),
  );
  $items['admin/config/mez/create_access_vocabulary'] = array(
    'title' => 'MEZ access vocabulary creation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mez_create_access_taxonomy_form'),
    'access arguments' => array('administer taxonomy'),
  );
  return $items;
}


/**
 * Form to create Instruments vocabualry
 */
function mez_create_instruments_taxonomy_form() {
  $form = array();
  $instruments_vocab = taxonomy_vocabulary_machine_name_load('instruments');
  if (!$instruments_vocab) {
    $form['help-text'] = array(
      '#markup' => t('You can create the Instruments vocabulary by clicking the Submit button.'),
      '#prefix' => '<div>',
      '#suffix' => '</div>',
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );
  }
  else {
    $form['help-text'] = array(
      '#markup' => t('The instruments vocabulary already exists.'),
      '#prefix' => '<div>',
      '#suffix' => '</div>',
    );
  }
  return $form;
}

/*
 * Submit handler for the mez__create_instruments_taxonomy_form.
 *
 * No & for $form_state as this function gets called directly with NULL
 * passed in.
 */
function mez_create_instruments_taxonomy_form_submit($form, $form_state) {
  $instruments = taxonomy_vocabulary_machine_name_load('instruments');
  if (!$instruments) {
    $vocabulary = array(
      'name' => 'Instruments',
      'machine_name' => 'instruments',
      'description' => 'Instruments',
      'hierarchy' => 1,
    );
    $instruments = (object) $vocabulary;
    taxonomy_vocabulary_save($instruments);
  }
  $instrument_terms = array(
    'string', 'wind', 'percussion', 'conductor'
  );
  $instrument_terms_hu = array(
    'vonós', 'fúvós', 'ütő', 'karmester'
  );
  foreach ($instrument_terms as $key => $term) {
    $instrument = array(
      'name' => $term,
      'name_field' => array('en' => array(array('value' => $term)), 'hu' => array(array('value' => $instrument_terms_hu[$key]))),
      'vid' => $instruments->vid,
      'weight' => $key,
    );
    $instrument_obj = (object) $instrument;
    taxonomy_term_save($instrument_obj);
  }

  $terms = taxonomy_get_term_by_name('string');
  $tid = reset($terms)->tid;
  $instrument_terms = array(
    'violin', 'viola', 'vionloncello', 'double bass',
  );
  $instrument_terms_hu = array(
    'hegedű', 'brácsa', 'cselló', 'bőgő',
  );
  foreach ($instrument_terms as $key => $term) {
    $instrument = array(
      'name' => $term,
      'name_field' => array('en' => array(array('value' => $term)), 'hu' => array(array('value' => $instrument_terms_hu[$key]))),
      'vid' => $instruments->vid,
      'weight' => $key,
      'parent' => $tid,
    );
    $instrument_obj = (object) $instrument;
    taxonomy_term_save($instrument_obj);
  }

  $terms = taxonomy_get_term_by_name('violin');
  $tid = reset($terms)->tid;
  $instrument_terms = array(
    '1st violin', '2nd violin',
  );
    $instrument_terms_hu = array(
    '1. hegedű', '2. hegedű',
  );
  foreach ($instrument_terms as $key => $term) {
    $instrument = array(
      'name' => $term,
      'name_field' => array('en' => array(array('value' => $term)), 'hu' => array(array('value' => $instrument_terms_hu[$key]))),
      'vid' => $instruments->vid,
      'weight' => $key,
      'parent' => $tid,
    );
    $instrument_obj = (object) $instrument;
    taxonomy_term_save($instrument_obj);
  }

  $terms = taxonomy_get_term_by_name('wind');
  $tid = reset($terms)->tid;
  $instrument_terms = array(
    'wood', 'brass',
  );
  $instrument_terms_hu = array(
    'fafúvós', 'rézfúvós',
  );
  foreach ($instrument_terms as $key => $term) {
    $instrument = array(
      'name' => $term,
      'name_field' => array('en' => array(array('value' => $term)), 'hu' => array(array('value' => $instrument_terms_hu[$key]))),
      'vid' => $instruments->vid,
      'weight' => $key,
      'parent' => $tid,
    );
    $instrument_obj = (object) $instrument;
    taxonomy_term_save($instrument_obj);
  }

  $terms = taxonomy_get_term_by_name('wood');
  $tid = reset($terms)->tid;
  $instrument_terms = array(
    'flute', 'oboe', 'clarinet', 'bassoon',
  );
  $instrument_terms_hu = array(
    'fuvola', 'oboa', 'klarinét', 'fagott',
  );
  foreach ($instrument_terms as $key => $term) {
    $instrument = array(
      'name' => $term,
      'name_field' => array('en' => array(array('value' => $term)), 'hu' => array(array('value' => $instrument_terms_hu[$key]))),
      'vid' => $instruments->vid,
      'weight' => $key,
      'parent' => $tid,
    );
    $instrument_obj = (object) $instrument;
    taxonomy_term_save($instrument_obj);
  }

  $terms = taxonomy_get_term_by_name('brass');
  $tid = reset($terms)->tid;
  $instrument_terms = array(
    'horn', 'trumpet', 'trombone', 'tuba',
  );
  $instrument_terms_hu = array(
    'kürt', 'trombita', 'harsona', 'tuba',
  );
  foreach ($instrument_terms as $key => $term) {
    $instrument = array(
      'name' => $term,
      'name_field' => array('en' => array(array('value' => $term)), 'hu' => array(array('value' => $instrument_terms_hu[$key]))),
      'vid' => $instruments->vid,
      'weight' => $key,
      'parent' => $tid,
    );
    $instrument_obj = (object) $instrument;
    taxonomy_term_save($instrument_obj);
  }
}
