<?php
/**
 * @file
 * Code for the MEZ settings feature.
 */

include_once 'mez_settings.features.inc';

/**
 * Implements hook_menu().
 */
function mez_settings_menu() {
  $items = array();
  // Frontpage
  $items['front'] = array(
    'page callback' => 'mez_settings_front',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Menu callback.
 */
function mez_settings_front() {
  return array(
    '#theme' => 'mez_frontpage',
  );
}

/**
 * Implements hook_theme().
 */
function mez_settings_theme($existing, $type, $theme, $path) {
  return array (
    'mez_frontpage' => array(
      'template' => 'mez-frontpage',
      'path' => drupal_get_path('theme', 'mez_bootstrap') . '/templates',
      'variables' => array(
      ),
    ),
  );
}

/**
 * Preprocess function for the frontpage.
 */
function mez_settings_preprocess_mez_frontpage(&$vars) {
  $background_page = node_load(variable_get('mez_background_page_nid'));
  $backgrounds = field_get_items('node', $background_page, 'field_media');

  // Get most recent sticky promoted node for the opening page.
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('status', 1)
    ->propertyCondition('promote', 1)
    ->propertyCondition('sticky', 1)
    ->propertyOrderBy('created', 'DESC')
    ->execute();
  if (isset($result['node'])) {
    $opening_nids = array_keys($result['node']);
  }
  $opening_nids = empty($opening_nids) ? 2098 : $opening_nids[0];
  $vars['opening'] = array(
    'node' => node_view(node_load($opening_nids), 'mez_frontpage'),
    'bg' => file_create_url($backgrounds[0]['uri']),
  );

  // Get the last news
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'mez_news')
    ->propertyCondition('status', 1)
    ->propertyCondition('promote', 1)
    ->propertyOrderBy('created', 'DESC')
    ->propertyCondition('nid', $opening_nids[0], '!=')
    ->execute();
  if (isset($result['node'])) {
    $news_nids = array_keys($result['node']);
  }
  $news_nids = empty($news_nids) ? 2098 : $news_nids[0];

  $vars['news'] = array(
    'node' => node_view(node_load($news_nids), 'mez_frontpage'),
  );

  // About
  $vars['about'] = array(
    'node' => node_view(node_load(13), 'mez_frontpage'),
    'bg' => file_create_url($backgrounds[1]['uri']),
  );

  // Archive
  $vars['archive'] = array(
    'bg' => file_create_url($backgrounds[2]['uri']),
  );
  $vars['site_name'] = variable_get_value('site_name');
  $vars['site_slogan'] = variable_get_value('site_slogan');
}

/**
 * Page preprocess hook.
 */
function mez_settings_preprocess_page(&$variables) {
  $variables['lang_chooser'] = locale_block_view('language');
  // Get a random background if not on the frontpage.
  if (!drupal_is_front_page()) {
    $background_page = node_load(variable_get('mez_background_page_nid'));
    $backgrounds = field_get_items('node', $background_page, 'field_media');
    $items_count = count($backgrounds);
    // Random number
    $delta = time() % $items_count;
    $url = file_create_url($backgrounds[$delta]['uri']);
    drupal_add_js(array('mezBg' => $url), 'setting');
    drupal_add_js(drupal_get_path('module', 'mez_settings') . '/js/mez_settings_background.js');
  }
}
