<?php

/**
 * @file
 * Content related stuff
 *
 */

/**
 * Implements hook_form_alter().
 */
function mez_content_form_alter(&$form, $form_state) {
  global $user;
  if (in_array($form['#id'], array('composer-node-form', 'piece-node-form'))) {
    // In the case of these two nodes ANT is used.
    $form['title_field']['#access'] = ($user->uid == 1);
  }
  $node_forms = array('composer-node-form,', 'piece-node-form', 'news-node-form', 'concert-node-form', 'page-node-form', 'person-node-form');
  if (in_array($form['#id'], $node_forms)) {
    $form['revision_information']['#access'] = ($user->uid == 1);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mez_content_form_piece_node_form_alter(&$form, $form_state) {
  array_unshift($form['actions']['submit']['#submit'], 'mez_content_piece_form_submit');
}

/**
 * Submit callback for the piece node form.
 *
 * Auto Nodetitle is not compatible with the Title module.
 */
function mez_content_piece_form_submit($form, &$form_state) {
  foreach ($form_state['values']['field_piece_title'] as $lang => $fpt) {
    if (!empty($fpt[0]['value'])) {
      $composer = node_load($form_state['values']['field_composer'][LANGUAGE_NONE][0]['target_id'])->title_field[LANGUAGE_NONE][0]['value'];
      $form_state['values']['title_field'][$lang][0]['value'] = $composer . ': ' . $fpt[0]['value'];
    }
  }
}
